### ISSUE TITLE
Add cards component

### ISSUE THREAD

**Issue by Tronic247** [finnhvman/matter#29]
Add cards component ex-https://codepen.io/DiEH/pen/jOPPzLV

**Comment by Tronic247** [comment]
Hello ? Is someone there ?

**Comment by anlexN** [comment]
加油

**Comment by Tronic247** [comment]
Is this framework dead ?

**Comment by Tronic247** [comment]
@anlexN meanwhile do you like [this](https://github.com/Tronic247/material) framework ?

**Comment by anlexN** [comment]
@Tronic247 so many ads!, oh my god.....

**Comment by Tronic247** [comment]
@anlexN I know and I'm removing the soon , Sorry for putting so many ads :{

**Comment by Tronic247** [comment]
https://github.com/Tronic247/material
