### ISSUE TITLE
Not an issue, but there are official Google pages using Matter

### ISSUE THREAD

**Issue by easrng** [finnhvman/matter#36]
The pages on the [Google DNS website](https://dns.google/) use Matter.

**Comment by easrng** [comment]
Oh huh, they aren't following the license.
> ```
> The above copyright notice and this permission notice shall be included in all
> copies or substantial portions of the Software.
> ```
The [CSS file](https://dns.google/static/836aebc6/matter.min.css) they have only has the name and version, no license notice.

**Comment by finnhvman** [comment]
Hey, thanks for notifying me! I know they are using it.

The license thing is not a big issue fore me, don't worry about it 🙂
