### ISSUE TITLE
matter-progress-circular doesnt seem to work with values

### ISSUE THREAD

**Issue by naveedahmed1** [finnhvman/matter#40]
The circular progress with class `matter-progress-circular`, seems to be working fine.

`<progress class="matter-progress-circular"></progress>
`

But with specified values, it doesn't work as expected:

`<progress class="matter-progress-circular" value="60" max="100"></progress>
`

Can you please guide?

**Comment by finnhvman** [comment]
Hey, sorry the determinate version (when you set a value) of the circular progress is not supported.
